/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as ModalsRouteImport } from './routes/modals'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as ChatDemoRouteImport } from './routes/chat-demo'
import { Route as ArtifactDemoRouteImport } from './routes/artifact-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionRoute = MotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalsRoute = ModalsRouteImport.update({
  id: '/modals',
  path: '/modals',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatDemoRoute = ChatDemoRouteImport.update({
  id: '/chat-demo',
  path: '/chat-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactDemoRoute = ArtifactDemoRouteImport.update({
  id: '/artifact-demo',
  path: '/artifact-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifact-demo': typeof ArtifactDemoRoute
  '/chat-demo': typeof ChatDemoRoute
  '/chats': typeof ChatsRoute
  '/modals': typeof ModalsRoute
  '/motion': typeof MotionRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tokens': typeof TokensRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifact-demo': typeof ArtifactDemoRoute
  '/chat-demo': typeof ChatDemoRoute
  '/chats': typeof ChatsRoute
  '/modals': typeof ModalsRoute
  '/motion': typeof MotionRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tokens': typeof TokensRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifact-demo': typeof ArtifactDemoRoute
  '/chat-demo': typeof ChatDemoRoute
  '/chats': typeof ChatsRoute
  '/modals': typeof ModalsRoute
  '/motion': typeof MotionRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tokens': typeof TokensRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifact-demo'
    | '/chat-demo'
    | '/chats'
    | '/modals'
    | '/motion'
    | '/projects'
    | '/settings'
    | '/tokens'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifact-demo'
    | '/chat-demo'
    | '/chats'
    | '/modals'
    | '/motion'
    | '/projects'
    | '/settings'
    | '/tokens'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/artifact-demo'
    | '/chat-demo'
    | '/chats'
    | '/modals'
    | '/motion'
    | '/projects'
    | '/settings'
    | '/tokens'
    | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactDemoRoute: typeof ArtifactDemoRoute
  ChatDemoRoute: typeof ChatDemoRoute
  ChatsRoute: typeof ChatsRoute
  ModalsRoute: typeof ModalsRoute
  MotionRoute: typeof MotionRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TokensRoute: typeof TokensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion': {
      id: '/motion'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof MotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modals': {
      id: '/modals'
      path: '/modals'
      fullPath: '/modals'
      preLoaderRoute: typeof ModalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-demo': {
      id: '/chat-demo'
      path: '/chat-demo'
      fullPath: '/chat-demo'
      preLoaderRoute: typeof ChatDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact-demo': {
      id: '/artifact-demo'
      path: '/artifact-demo'
      fullPath: '/artifact-demo'
      preLoaderRoute: typeof ArtifactDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactDemoRoute: ArtifactDemoRoute,
  ChatDemoRoute: ChatDemoRoute,
  ChatsRoute: ChatsRoute,
  ModalsRoute: ModalsRoute,
  MotionRoute: MotionRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TokensRoute: TokensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
